PhpDocToCommentFixer - Ignore annotations
FriendsOfPHP/PHP-CS-Fixer pull request #4649
Opened 2019-11-18 13:59 UTC by localheinz

This PR

* [x] adds a failing test case
* [ ] adjusts `PhpDocToComment` fixer to ignore annotations

💁‍♂ For reference, see https://github.com/vimeo/psalm/issues/2344.

/cc @theseer

2019-11-21 07:54 UTC, localheinz commented
@kubawerlos 

> Can we go with option `ignored_tags` like for [`CommentToPhpdocFixer`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4385/files) instead?

Makes a lot of sense, will adjust!

2020-01-06 12:12 UTC, Taluu commented
I don't think adding just an option to "ignore some tags" is really dx-friendly. There are A LOT of annotations tags (doctrine, psalm, php ea inspections, ... and so on).

I think that if a line in a comment starts with `* @`, it should be safe to consider that it's an annot...

2020-01-06 13:52 UTC, kubawerlos commented
> I think that if a line in a comment starts with `* @`, it should be safe to consider that it's an annot...

@Taluu it seems you are totally missing the point of [PHPDoc](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#3-definitions).

The first criteria if a comment is/should be PHPDoc is: if it's placed before the structural element or not, so relying on the content is not a solution.

> There are A LOT of annotations tags (doctrine, psalm, php ea inspections, ... and so on).

Doctrine's tags must be in PHPDocs, so this is not really good example.

2020-01-06 13:57 UTC, Taluu commented
> The DocBlock is the combination of a DocComment, which is a type of comment, and a PHPDoc entity.

DocBlocks (which are also annotations, as PHPDocs tags actually) shouldn't be transformed then.

2020-01-06 14:37 UTC, kubawerlos commented
Why so? If they are not placed before the structural element they should.

2020-01-06 14:39 UTC, Taluu commented
It's not because they're not placed above a structural element that they shouldn't be an annotation.

Think of `@var`, `@codeCoverageIgnore`, ... and so on. `@var` is a valid phpdoc tag, yet not always used on a structural element...

2020-01-06 15:00 UTC, kubawerlos commented
>  `@var` is a valid phpdoc tag, yet not always used on a structural element...

Like when? I'd say it always is.

2020-01-06 19:24 UTC, theseer commented
> > `@var` is a valid phpdoc tag, yet not always used on a structural element...
> 
> Like when? I'd say it always is.

Like at any inline location where a type declaration might be needed to get IDE autocomplete or have psalm annotations:

```php
/** @var $foo SomeType */
$foo = $obj->someMethod();
```

Not saying a "proper" fix would probably be to have correct return type on the method `someMethod` - but that may not be an option.

Or, scroll back to the top and read the referenced issue at psalm (https://github.com/vimeo/psalm/issues/2344) and the very reason why @localheinz created the PR.

2020-01-06 19:45 UTC, theseer commented
Actually, I think there are various - potentially arbitrary - reasons to have inline docblocks with annotations: To disable inspections, to add assertions for or otherwise configure static analyzers, code coverage generation, ...

Having `PhpDocToCommentFixer` unconditionally replace inline docblocks breaks all of them. It makes perfect sense to replace mere comments that just happend to use the "wrong" syntax of course, but a docblock regardless of its location with any type of annotation in it is more than just a comment.

2020-01-06 21:08 UTC, kubawerlos commented
Adding `/** @var $foo SomeType */` before variable is perfectly fine usage of PHPDoc.

> To disable inspections, to add assertions for or otherwise configure static analyzers, code coverage generation, ...

All these reasons seem to have defined a set of annotations that would be uses -> thus the idea of having a list of tags to ignore.

> Having `PhpDocToCommentFixer` unconditionally replace inline docblocks breaks all of them.

Not unconditionally, simply according to the PSR5, which clarifies what PHPDoc is and what isn't.

If your proposition is to ignore PSR5 and trying to guess if PHPDoc should be converted comment basing of its content I think you need to create an issue to discuss it there - not here in a pull request.

2020-01-08 07:47 UTC, SpacePossum commented on src/Tokenizer/Analyzer/CommentsAnalyzer.php
> +        return 1 === Preg::match('#\/\*{2}\s+.*@\w+#m', $token->getContent());
shouldn't this also do a type check? For example this string literal `$a = "/** @var int $foo */"` and HEREDOC/NOWDOC s etc., should all not be considered annotations I think?

2020-04-10 10:55 UTC, julienfalque commented
I've got this issue a few times and I admit it is quite annoying. Adding a whitelist option would keep current stricly PSR-5 compliant behavior but I think it's not very DX-friendly and I prefer ignoring any `/**` comment that starts with a tag.

2020-05-12 17:00 UTC, SpacePossum commented
I like the the proposal of @kubawerlos , but I can see why it might be a bit of trouble to configure the exceptions. To be clear `@var` already works fine AFAIK.

The cases I found are those from popular SCA's like `@psalm-suppress`  (but i prefer baselines file now).

I propose to add the ignore option in the next minor release. On the next major we release with a new default value for it containing `@psalm-suppress` and some other that people can provide here that are biting them.

2020-07-25 10:48 UTC, GrahamCampbell commented
For some background, the reason this fixer changes some phpdoc containing annotations to comments is because of the proposed PSR phpdoc spec, which says that doc comments must document structural elements, so the sort of doc comments you have in your tests are illegal according to that spec.

HOWEVER, things have changed since that spec was first drafted, and the role of phpdoc has changed. No longer is phpdoc just for documentation generators to show the public api of classes, but these days we have genuinely usable static analyzers, and indeed these tools are now dictating the syntax (and semantics) of phpdoc (and annotations), and the sensible locations for phpdoc within a piece of code has changed, to allow for, for example, the specification of the type of an internal variable: something that was not relevant, even in 2014 (since the tooling was just not there, back then).

With all this in mind, I think this is a good change, in principle. The outstanding review comments need to be addressed, as do the failing tests, then this PR should be ready for 2nd reviews (and merge, if the php-cs-fixer team are happy!). ;)

2020-07-25 10:49 UTC, GrahamCampbell commented
Unrelated, but phpstorm processes comments as phpdoc, in error. Kinda annoying, but I guess they do it because:

1. not everyone understands the difference between a comment and a doc comment
2. people have run php-cs-fixer on their code and it's changed their doc comments to comments :trollface:

2020-08-11 14:46 UTC, julienfalque commented on src/Tokenizer/Analyzer/CommentsAnalyzer.php
> +    public function isAnnotation(Token $token)
Shouldn't it accepts the `Tokens` list and an index like other methods do?

2020-08-11 14:49 UTC, julienfalque commented on tests/Tokenizer/Analyzer/CommentsAnalyzerTest.php
> +            ],
Maybe we can add cases like e.g. `/** no "at" sign */` and `/** @ followed by a space */`?

2021-02-22 18:09 UTC, kubawerlos requested changes

2021-02-22 18:09 UTC, kubawerlos commented on src/Fixer/Phpdoc/PhpdocToCommentFixer.php
> +            if ($commentsAnalyzer->isAnnotation($token)) {
Can we have this configurable to maintain BC? An option `ignore_annotations` (with default to `false`) seems the way.

2021-03-23 17:12 UTC, VincentLanglet commented
What's the status of this ?
I started https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5572 before discovering this PR.

The fact that `/** @psalm- */` annotation are modified is really annoying.

2021-06-16 12:10 UTC, masi commented
Please, merge this code. Having @psalm-suppress (and possible many other linter/checker annotations) as collateral damage is no fun.

2021-06-16 17:15 UTC, kubawerlos commented
@masi as you can see there is not agreement in the discussion - you can always disable the rule if does any harm to your code.

2021-06-16 18:21 UTC, masi commented
But the rule is fine for all comments unless they contain (certain) annotations.
Of course if Psalm would allow it's annotations within standard comments I would also be happy :)

2021-06-16 18:34 UTC, kubawerlos commented
How is it fine? In the current state it does not convert to comment if there is any annotation in PHPDoc which makes the description "Docblocks should only be used on structural elements" not being true.

I'd prefer this one to go through: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5572

2021-06-16 20:18 UTC, masi commented
I don't care about what the PHPDoc . I'm using annotations for my IDE and other tools. Eg I'm using Psalm and this tool insists on docblocs for its annotations.

For sake of consistency I prefer to use a single * for normal comments.

Perhaps I failed to see the subtleties. If #5572 is in, I'm happy.

Sorry, for any misunderstandings and the added confusion.

2021-06-17 17:09 UTC, julienfalque commented
I'm still in favor of *not* adding any option and ignore all `/** ... */` comments as soon as they contain an annotation by default. Maybe we could rename the fixer to something like `DocCommentToRegularCommentFixer` to avoid the PHPDoc rules?

Anyway we need to make a decision here /ping @keradus @SpacePossum

2021-06-18 08:00 UTC, masi commented
> I'm still in favor of _not_ adding any option and ignore all `/** ... */` comments as soon as they contain an annotation by default.
Make this behaviour an opt-in and everybody should be happy.

> Maybe we could rename the fixer to something like `DocCommentToRegularCommentFixer` to avoid the PHPDoc rules?
Or have two rules.

2022-08-07 14:03 UTC, VincentLanglet commented
I think this can be closed since the feature was introduced by https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5572

2022-08-07 14:08 UTC, closed without merging