DX: Drop speedtrap phpunit listener
FriendsOfPHP/PHP-CS-Fixer pull request #5429
Opened 2021-01-10 13:06 UTC by keradus

PHPUnit now manage time of execution on it's own, no need for plugin.

trying to solve random test timeouts at Travis, maybe there is conflict between native mechanism and plugin.

2021-01-11 20:49 UTC, kubawerlos approved these changes

2021-01-12 22:35 UTC, kubawerlos requested changes
@keradus you meant GitHub Actions, right?

Addiing `timeoutFor*Tests` seems not helping - can you also add `defaultTimeLimit` (`10`?)? This seems to helping (tested on local machine).

2021-01-13 21:29 UTC, keradus commented
> you meant GitHub Actions, right?

indeed :+1:
after 9 years of PHP CS Fixer on Travis, still kind of falling back to it when thinking about CI

2021-01-13 21:30 UTC, keradus commented
> can you also add `defaultTimeLimit`

good idea

2021-01-13 23:49 UTC, keradus commented
i extracted non-speedtrap listener changes into #5435 and do some more work there

2021-01-14 01:23 UTC, merged