Fix spacing for arrow functions
FriendsOfPHP/PHP-CS-Fixer pull request #5579
Opened 2021-03-27 09:47 UTC by krzysztofrewak

Now arrow functions spacing is broken and it's working like this:
```php
array_filter([1, 2, 3, 4], fn (int $i): bool => $i % 2 === 0);
```

PHPStorm and other web sources have something like this:
```php
array_filter([1, 2, 3, 4], fn(int $i): bool => $i % 2 === 0);
```

I took care about previous PHP versions (without `T_FN` token) too.

2021-03-28 02:35 UTC, GrahamCampbell commented
This is not a "fix" but a breaking change, as we can see from the tests.

2021-03-28 02:36 UTC, GrahamCampbell commented
We have explict tests that expect the space to be added in there.

2021-03-29 06:25 UTC, krzysztofrewak commented
> There are explicit tests that expect the space to be added in there.

@GrahamCampbell, do you want me to change these tests? Or are you questioning the legitimacy of these changes? In PHP docs there're multiple cases with `fn()` withou spaces: https://www.php.net/manual/en/functions.arrow.php:

```php

<?php

$y = 1;
 
$fn1 = fn($x) => $x + $y;
// equivalent to using $y by value:
$fn2 = function ($x) use ($y) {
    return $x + $y;
};

var_export($fn1(3));
?>
```

2021-03-29 14:09 UTC, GrahamCampbell requested changes
👎 This is a breaking change. At best, this could be changed to be a config option, but certainly not the default changed.

2021-03-29 14:09 UTC, GrahamCampbell requested changes

2021-03-29 14:09 UTC, GrahamCampbell commented on tests/Fixtures/Integration/misc/PHP8_0.test
> -    $callable = fn () => throw new Exception();
Breaking change

2021-03-29 14:09 UTC, GrahamCampbell commented on tests/Fixtures/Integration/misc/PHP7_4.test
> -$foo = fn ($v) => (string) $v;
Breaking change.

2021-03-29 17:26 UTC, kubawerlos requested changes
The tests you have changed (and the code you did not, which makes the build failing) are there exactly to check the space is added.

It was done in [this](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4600) PR, see especially file `tests/Fixer/FunctionNotation/FunctionDeclarationFixerTest.php`.

Even if we want this behaviour to be allowed, it should not be in `NoSpacesAfterFunctionNameFixer` as the arrow function does not have name, but in `FunctionDeclarationFixer` - most likely as option `none`/`single` (by default `single`) added.

2021-03-29 17:26 UTC, kubawerlos commented on src/Fixer/FunctionNotation/NoSpacesAfterFunctionNameFixer.php
> +    private function getFunctionTokenKinds()
Why did you rename the function? The new name is misleading.

2021-06-15 16:44 UTC, closed without merging