GroupImportFixer severely broken
FriendsOfPHP/PHP-CS-Fixer pull request #5615
Opened 2021-04-09 13:37 UTC by Leprechaunz

Fixes #5408

2021-04-09 15:07 UTC, kubawerlos requested changes

2021-04-09 15:07 UTC, kubawerlos commented on tests/Fixer/Import/GroupImportFixerTest.php
>  ',
Let'a add a test with multiple namespaces with the same length, with input data like:
```php
<?php
use Framework\Foo\Class1;
use Framework\Foo\Class2;
use Framework\Bar\Class3;
use Framework\Bar\Class4;
use Framework\Bar\Class5;
use Framework\Baz\Class6;
use Framework\Foo\Class7;
```

2021-04-10 13:53 UTC, kubawerlos approved these changes
Cool 👍🏼

2021-04-11 18:07 UTC, keradus commented
Thank you @Leprechaunz.

2021-04-11 18:07 UTC, merged