group_import removes import type when mixing multiple types
FriendsOfPHP/PHP-CS-Fixer pull request #5618
Opened 2021-04-10 23:57 UTC by Leprechaunz

Fixes #5346

2021-04-11 08:33 UTC, kubawerlos requested changes

2021-04-11 08:33 UTC, kubawerlos commented on src/Tokenizer/Analyzer/Analysis/NamespaceUseAnalysis.php
> +    public function getType()
Let's have some tests for this one in `NamespaceUseAnalysisTest`.

2021-04-11 10:22 UTC, kubawerlos approved these changes

2021-04-11 18:13 UTC, keradus commented
Hey @Leprechaunz, can you resolve conflict by rebasing the PR, please?

2021-04-12 11:22 UTC, Leprechaunz commented
@keradus resolved conflicts ✅

2021-04-14 17:04 UTC, keradus commented
Thank you @Leprechaunz.

2021-04-14 17:04 UTC, merged