[typo] add correct backquotes
FriendsOfPHP/PHP-CS-Fixer pull request #5710
Opened 2021-05-10 21:25 UTC by PhilETaylor

sorry found another typo of backquotes while reading in bed :)

2021-05-11 07:14 UTC, julienfalque requested changes

2021-05-11 07:14 UTC, julienfalque commented on doc/usage.rst
> +* ``xml`` follows the ``own XML schema </doc/schemas/fix/xml.xsd>``
The formatting was correct here to create links: `` `text <URL>` ``. Now the syntax is rendered literally, please revert.

2021-05-12 09:21 UTC, GrahamCampbell approved these changes

2021-05-13 18:39 UTC, keradus commented
Thank you @PhilETaylor.

2021-05-13 18:39 UTC, merged