Add support for `namespace` to `single_space_after_construct`
FriendsOfPHP/PHP-CS-Fixer pull request #5727
Opened 2021-05-21 08:22 UTC by julienfalque

Closes #3728.

2021-05-23 17:44 UTC, GrahamCampbell commented
Isn't changing the default a breaking change?

2021-05-23 17:48 UTC, GrahamCampbell requested changes

2021-05-23 17:48 UTC, GrahamCampbell commented on tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
> +    }
Missing some cases:

```php
<?php

namespace // comment
Foo;
```

```php
<?php

namespace /* comment */ Foo;
```

2021-05-24 17:42 UTC, julienfalque commented on tests/Fixer/LanguageConstruct/SingleSpaceAfterConstructFixerTest.php
> +    }
Added, thank :+1:

2021-05-24 17:44 UTC, julienfalque commented
> Isn't changing the default a breaking change?

This already happened (e.g. #5406) but I would say it's fine here: it's part of the initial intent of this rule but was overlooked. So this PR is a an enhancement/bugfix rather than a new feature.

2021-05-24 18:45 UTC, kubawerlos approved these changes

2021-05-25 21:26 UTC, keradus commented
Thank you @julienfalque.

2021-05-25 21:26 UTC, merged