RandomApiMigrationFixer - add option to migrate to "random_int"
FriendsOfPHP/PHP-CS-Fixer pull request #5747
Opened 2021-05-27 12:29 UTC by SpacePossum

2021-06-07 11:45 UTC, julienfalque approved these changes

2021-06-21 15:16 UTC, kubawerlos approved these changes

2021-06-27 13:10 UTC, keradus commented on src/Fixer/Alias/RandomApiMigrationFixer.php
> +                    'rand' => 'mt_rand', // TODO change to `random_int` as default on 4.0
```suggestion
                    'rand' => 'mt_rand', // @TODO change to `random_int` as default on 4.0
```

so I can find it later

2021-06-27 13:14 UTC, keradus commented on tests/Fixer/Alias/RandomApiMigrationFixerTest.php
> +    public function testFixToRandomInt()
we already have tests for `random_int`:
- without params: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.19/tests/Fixer/Alias/RandomApiMigrationFixerTest.php#L96-L100
- with params: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/2.19/tests/Fixer/Alias/RandomApiMigrationFixerTest.php#L163-L167

2021-06-27 13:16 UTC, keradus commented
> RandomApiMigrationFixer - add option to migrate to "random_int"

it's *not* adding any option - one can already migrate to `random_int`. Even `PHP70MigrationRisky` set is doing that

2021-06-27 13:17 UTC, keradus requested changes
- please drop duplicated tests
- this is not enhancement PR, I see no new possibilities coming with this PR, the main value I see is documenting not-fully-documented random_int option

2021-07-17 13:18 UTC, keradus commented on tests/Fixer/Alias/RandomApiMigrationFixerTest.php
> +    public function testFixToRandomInt()
@SpacePossum can you take a look pls?

2021-07-26 15:02 UTC, SpacePossum commented
I've removed the tests

2021-07-26 15:13 UTC, SpacePossum commented
I was wrong thinking adding support here indeed. It is because this is also supported currently:
```
            [
                '<?php foo();',
                '<?php rand();',
                ['replacements' => ['rand' => 'foo']],
            ],
```
making it a more generic function renaming rule than I expected. I was expecting known PHP random methods as input _and_ as output.
Anyway, besides the docs this PR also adds proper argument counts for using `random_int` as input FWIW

2021-07-28 08:07 UTC, SpacePossum commented
sca fail seems unrelated

2021-07-29 21:56 UTC, keradus approved these changes

2021-07-29 21:58 UTC, keradus commented
Thank you @SpacePossum.

2021-07-29 21:58 UTC, merged