NoAlternativeSyntaxFixer - Add option to not fix non-monolithic PHP code
FriendsOfPHP/PHP-CS-Fixer pull request #5773
Opened 2021-06-19 13:54 UTC by paulbalandan

The alternative syntax for control structures is especially useful when mixed with HTML or used in templating. When the code involved is big it can get tricky to keep track of the `{` and `}`. This is where `endif`, `endforeach`, etc. comes advantageous. These alternates give you a better way to match code blocks when mixed with HTML contents.

This PR adds an option to exclude fixing this "non-monolithic" code.

2021-07-30 14:18 UTC, SpacePossum commented
Hi and thanks for the PR!

Could you restore the current samples and add a single new sample that shows the behavior of the new flag? Secondly, I would prefer the new flag be called as to what it does and not the negative, like `fix_monolithic` with `true/false` and the default set to maintain the current behavior. 
Wonder what the others think of this change, so maybe wait for more opinions before putting more effort in the PR :)

2021-07-30 15:22 UTC, paulbalandan commented
> Could you restore the current samples and add a single new sample that shows the behavior of the new flag?

This is initially what I did but tests fail saying there should be no more than 1 code sample with default configuration for a configurable fixer.

2021-08-31 06:23 UTC, SpacePossum commented
Thanks for the changes! 
I like where this is going, just a few minors. However, you might want to get some of the members to say of they like this before putting more time in it. 

For me the naming of the option must be renamed to a positive, for example: `only_fix_monolithic_code`.
I think we only need two examples, the current one for the default configuration you got in the PR now and only one of 3 with the new configuration option, I see issue with the previous request now, sorry about that :+1: 
The `isCandidate` check can be a one liner without an `if`, like `return $tokens->hasAlternativeSyntax() && (!$this->configuration['only_monolithic_code'] || $tokens->isMonolithicPhp())`

2021-09-01 06:21 UTC, SpacePossum approved these changes

2021-09-02 17:28 UTC, keradus requested changes
I am strongly against fixing non-monolithic code. The only use case I can imagine is when fixing PHP with HTML for some templating purposes.  One should rather switch to proper template system, like twig or mustache.

2021-09-02 21:54 UTC, SpacePossum commented
the PR aims to add an option to not fix non-monolithic code, is this what you want as you are strongly against fixing non-monolithic code? or do you request to change the default behavior (currently the fixer does fix non-monolithic code) ?

2021-09-04 14:56 UTC, paulbalandan commented
I would also like this to be clarified. This PR now adds an option to skip fixing non-monolithic code, which is current behavior.

2021-09-04 17:15 UTC, keradus commented
got you :+1: 
Then, let's add a TODO for v4 to change the default of newly introduced option

2021-09-05 12:39 UTC, SpacePossum approved these changes

2021-09-05 13:19 UTC, SpacePossum commented
Thank you @paulbalandan.

2021-09-05 13:19 UTC, merged