fix(static-lambda-fixer): consider parent:: as a possible reference to $this
FriendsOfPHP/PHP-CS-Fixer pull request #5783
Opened 2021-06-29 15:01 UTC by fancyweb

2021-06-29 16:20 UTC, kubawerlos requested changes

2021-06-29 16:20 UTC, kubawerlos commented on src/Fixer/FunctionNotation/StaticLambdaFixer.php
> +            if ($tokens[$i]->isGivenKind(T_STRING) && 'parent' === strtolower($tokens[$i]->getContent())) {
```suggestion
            if ($tokens[$i]->equals([T_STRING, 'parent'], false)) {
```

2021-06-30 14:58 UTC, kubawerlos approved these changes

2021-06-30 15:11 UTC, julienfalque approved these changes

2021-07-17 13:26 UTC, keradus commented
Thank you @fancyweb.

2021-07-17 13:26 UTC, merged