DX: ProjectCodeTest - fix detection by testExpectedInputOrder
FriendsOfPHP/PHP-CS-Fixer pull request #5925
Opened 2021-08-30 21:42 UTC by keradus

2021-08-31 05:51 UTC, kubawerlos requested changes

2021-08-31 05:51 UTC, kubawerlos commented on tests/Fixer/FunctionNotation/NullableTypeDeclarationForDefaultNullValueFixerTest.php
>          }
```suggestion
        $this->doTest($expected, $input);
```

2021-08-31 12:55 UTC, keradus commented
@fabpot , fabbot.io is wrong here, it assumes it runs on Symfony. maybe it could run rules depending on repos (default rules or default+Symfony rules?)

2021-08-31 16:32 UTC, kubawerlos approved these changes

2021-09-04 11:55 UTC, GrahamCampbell commented
Merge conflicts. 😭

2021-09-04 12:46 UTC, keradus commented
not sure what this comment brings to discussion, each of us can see it, no need to fingerprint it :shrug:

2021-09-04 13:26 UTC, merged