Remove superfluous annotation @abstract and @final
FriendsOfPHP/PHP-CS-Fixer pull request #6011
Opened 2021-09-15 08:27 UTC by liquid207

Closes #5985

2021-09-15 09:35 UTC, julienfalque reviewed
Looking great!

2021-09-15 09:35 UTC, julienfalque commented on tests/Fixer/Phpdoc/NoSuperfluousPhpdocTagsFixerTest.php
> +            'abstract annotation in function' => [
Please add some tests that show the annotations are not removed when the class or the functions are not marked as final/abstract.

2021-09-15 09:37 UTC, julienfalque commented
Also, can you edit your commit message so that `@abstract` and `@final` are surrounded with `` ` ``? This would prevent people from being notified unnecessarily.

2021-09-15 10:07 UTC, julienfalque approved these changes

2021-09-15 10:27 UTC, SpacePossum commented
Thanks for picking this up!

I did a little test and there are some cases that are not fixed as expected I think

```diff
[12:25 PM]-[possum@aquarium]-[~/work/PHP-CS-Fixer]-[git feature/improve-no-superfluous-phpdoc-tags-fixer] 
$ php php-cs-fixer fix test.php -vvv --dry-run --diff --rules=no_superfluous_phpdoc_tags
Xdebug: [Step Debug] Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(
PHP CS Fixer 3.2.0-DEV River by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.23
Loaded config default from "/home/possum/work/PHP-CS-Fixer/.php-cs-fixer.dist.php".
Paths from configuration file have been overridden by paths provided as command arguments.
F                                                                                                                                                                                                      1 / 1 (100%)
Legend: ?-unknown, I-invalid file syntax (file ignored), S-skipped (cached or empty file), .-no changes, F-fixed, E-error
   1) PHP-CS-Fixer/test.php (no_superfluous_phpdoc_tags)
      ---------- begin diff ----------
--- /home/possum/work/PHP-CS-Fixer/test.php
+++ /home/possum/work/PHP-CS-Fixer/test.php
@@ -2,7 +2,6 @@
 final class B{}
 
 /**
- * @final
  */
 class Foo {
 }
```

2021-09-15 10:27 UTC, SpacePossum requested changes
please check comment and CI

2021-09-16 10:11 UTC, GrahamCampbell commented
A breaking change, no? Shouldn't we add configuration to the fixer, off by default?

2021-09-16 18:15 UTC, julienfalque commented
No, this is part of what the rule is intended to do, but was not implemented yet. If you want to have "no superfluous PHPDoc tags", you likely don't want to keep superfluous `@final`/`@abstract`.

2021-09-18 13:31 UTC, SpacePossum commented
I left a PR on your fork for even more fixes, let me know what you think

2021-09-19 01:20 UTC, liquid207 commented
@SpacePossum I have added you commit to my branch.

2021-09-19 18:16 UTC, SpacePossum commented
Thank you @liquid207.

2021-09-19 18:16 UTC, merged