FullyQualifiedStrictTypesFixer - fix same classname is imported from …
FriendsOfPHP/PHP-CS-Fixer pull request #6197
Opened 2021-12-20 10:34 UTC by SpacePossum

…global and non-global namespace

closes #4726

2022-01-05 12:35 UTC, SpacePossum commented on tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
> +        \Ping\Something $something,
I think the current fixer is wrong here, removing the leader `\` within the current namespace changes the type that is supposedly used here

2022-01-05 12:36 UTC, SpacePossum commented on tests/Fixer/Import/FullyQualifiedStrictTypesFixerTest.php
> +        \Foo\Bar\Baz\Buz $other4
same here

2022-01-05 12:59 UTC, SpacePossum commented
note to self; make coverage report of the fixer to see if all paths are covered

2022-01-21 22:55 UTC, kubawerlos requested changes
Let's add a test case for:
```php
<?php
namespace Foo\Bar;
function test(\Foo\Bar $x) {}
```

2022-01-22 15:41 UTC, SpacePossum commented
nice edge-case, thanks :+1:  , patched

2022-01-22 19:58 UTC, kubawerlos approved these changes

2022-01-22 20:40 UTC, closed without merging