Comma not added to multiline `new static`
FriendsOfPHP/PHP-CS-Fixer pull request #6380
Opened 2022-05-11 20:20 UTC by dpi

Trailing comma is not added to multi-line function invocations In code such as.

```
class Foo {

  public static function create(): static {
    return new static(
      'foo',
      'bar'
    );
  }

}
```

I expect a comma to be added directly after 'bar', such that code becomes:

```
class Foo {

  public static function create(): static {
    return new static(
      'foo',
      'bar',
    );
  }

}
```

2022-05-11 20:22 UTC, dpi commented
Using `return new self()` did work however.

2022-05-12 21:25 UTC, kubawerlos requested changes
@dpi nice catch, can you add some test to prevent regression?

2022-05-15 10:08 UTC, GrahamCampbell approved these changes

2022-05-15 10:44 UTC, GrahamCampbell commented
(my approval is subject to tests being added)

2022-05-30 11:21 UTC, dpi commented
Tests are in

@GrahamCampbell

2022-05-30 16:37 UTC, SpacePossum commented
@dpi thanks so much for adding the tests! The PR looks better and better. Currently the CI fails because of the CS of the changes, can you run the fixer itself on its code and have a look at the changes?

2022-05-31 14:46 UTC, dpi commented
lint changed, its not clear to me how to get the other tests to run?

2022-05-31 15:53 UTC, SpacePossum commented
seems your PR got hit by https://github.com/symfony/symfony/pull/45361  , which is not related to your changes, so this CI failure doesn't need to be fixed in your PR

2022-05-31 15:54 UTC, dpi commented
Huzzah!

2022-05-31 15:54 UTC, kubawerlos approved these changes

2022-08-13 20:48 UTC, julienfalque approved these changes

2022-08-13 20:48 UTC, merged

2022-08-13 20:48 UTC, julienfalque commented
Thank you @dpi.